### ISSUE TITLE
Support scalable_msize() or similar function for memory pools API

### ISSUE THREAD

**Issue by michalbiesek** [01org/tbb#108]
Hi,
I'm using TBB API related to pool management:
https://github.com/01org/tbb/blob/ab775e45cbda7115de05fa5465321f6324b2ac6c/include/tbb/scalable_allocator.h#L185-L195
I was trying to obtain size of block of memory allocated by API mentioned above.
I was trying to use scalable_msize() function, but unfortunately when I used debug version of TBB library to **assure that I'm using library correctly** I hit the assert:
https://github.com/01org/tbb/blob/314792356bf75f4a190277536aea543b9b6b310b/src/tbbmalloc/frontend.cpp#L2611
Could You please provide support function in official API for memory pool management to get the information about of allocated memory block using memory pool API (e.g. pool_malloc() function )

**Comment by nik-ponomarev** [comment]
Hi @michalbiesek, notifying you that the problem was resolved by introducing new Memory Pool API:
```cpp
pool_msize(MemoryPool *memPool, void *object)
```
It works just like `scalable_msize` but accepts a pool pointer, from which this object was allocated. In debug, this function also checks whether this pointer was really allocated from the provided memory pool.
