### ISSUE TITLE
Documentation for tbbmalloc huge pages is misplaced and incomplete

### ISSUE THREAD

**Issue by anton-malakhov** [01org/tbb#21]
It is hard to find how to enable huge pages for tbbmalloc in TBB documentation. It is mentioned very deeply in "[C interface...](https://www.threadingbuildingblocks.org/docs/help/reference/memory_allocation/c_interface_to_scalable_allocator.html)" section of TBB allocator but not in "Environment" section to which it logically belong. Also, it does not hint how to enable huge pages on a system.

Just FYI, this info from [this pdf ](http://www.prace-ri.eu/IMG/pdf/Best-Practice-Guide-Knights-Landing.pdf) was very helpful:

* to configure Linux for huge pages: `# echo 2000 > /proc/sys/vm/nr_hugepages`
* to enable huge pages for TBB malloc `$ export TBB_MALLOC_USE_HUGE_PAGES=1`
* for the ways to replace standard allocator see [this](https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Automically_Replacing_malloc.html)

**Comment by akukanov** [comment]
Anton, thanks for the feedback.

We will add "huge memory pages" as well as a few other keywords to the documentation index so that the information is easier to find. I disagree that it should be separated into "Environment" section, but we will think if it makes sense to add a link there.

As for the ways to enable huge pages on a system, I do not think the TBB documentation is the right place for such information. But we will add a "hint" to check OS documentation or ask the system administrator.

**Comment by elftech** [comment]
@anton-malakhov ,  the steps you posted is to use pre-allocated huge pages. Anyway to support transparent huge pages ? I searched and could not find a proper one.

**Comment by alexey-katranov** [comment]
TBB malloc should support transparent huge pages. Consider the note in [documentation](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/memory_allocation/c_interface_to_scalable_allocator.html#c.TBBMALLOC_USE_HUGE_PAGES)  about `TBBMALLOC_USE_HUGE_PAGES`
> For now, this allocation mode is only supported for Linux* OS. It works with both explicitly configured and transparent huge pages

**Comment by elftech** [comment]
@alexey-katranov , it support thp by both setting system thp parameter to 'always' and setting TBBMALLOC_USE_HUGE_PAGES to '1'. However, no support when the system thp parameter is 'madvice'.  #526   A other memory allocation library,  jemalloc supports either setting to 'always' or 'madice'.
