### ISSUE TITLE
Dr. Memory tool (http://www.drmemory.org/) reports UNADDRESSABLE ACCESS errors within TBB code

### ISSUE THREAD

**Issue by alexei37** [01org/tbb#23]
Please refer to https://github.com/DynamoRIO/drmemory/issues/2004 for a detailed description.

The errors are reported for memory addresses returned by **task::prefix()** method (usually within constructors for the **task** class).

Will appreciate your opinion on whether these are likely to be false positives reported by _Dr. Memory_, or if this is indeed an issue within _TBB_.

Thanks!

**Comment by alexey-katranov** [comment]
I suppose it is a false positive because a pointer to a task is not a pointer to the first byte of allocated memory. You can see in [scheduler.cpp:322](https://github.com/01org/tbb/blob/a2cfdfe946933cbe38bffe1d8086ae36f06691a3/src/tbb/scheduler.cpp#L322) that a task pointer is shifted to the right on the `task_prefix_reservation_size` number of bytes. Therefore, when we calculate a prefix pointer in [task.h:904](https://github.com/01org/tbb/blob/dc82836bb9c82053bc2c89a7a8489a6118c934f8/include/tbb/task.h#L904) we shift to the left safely (`sizeof(task_prefix)`<=`task_prefix_reservation_size` [scheduler_common.h:163](https://github.com/01org/tbb/blob/a2cfdfe946933cbe38bffe1d8086ae36f06691a3/src/tbb/scheduler_common.h#L163))

**Comment by alexei37** [comment]
Response from _Dr. Memory_ developers:

> Yes, a custom allocator that pads can result in problems tracking which addresses are addressable. The typical solution is to annotate the allocator so that the tool knows which range of memory it allocated. That feature is not yet present in Dr. Memory (#107). Do your custom allocators already have Valgrind annotations? If so the plan is for Dr. Memory to support those.

[Alexey](https://github.com/alexey-katranov), could you please disclose some info on how **NFS_Allocate()** and **NFS_Free()** work in _TBB_ code; in particular, whether they have "_Valgrind_ annotations", and, if not, if there are plans do add them?

**Comment by alexey-katranov** [comment]
I have answered in [the Dr.Memory related thread](https://github.com/DynamoRIO/drmemory/issues/2004).
