### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [01org/tbb#78]
Would you like to [replace any double quotes](https://github.com/01org/tbb/blob/615bb971db8784ab6c005a856e8ed3e8cea61d9b/include/tbb/task.h#L24 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by alexey-katranov** [comment]
What can be the reason not to use double quotes in include statements?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by alexey-katranov** [comment]
I am not sure that I understand the concern about “a duplicated file search" because any TBB header file should be found (otherwise, something is broken) and I believe the preprocessor is quite smart to optimize the search.
In accordance with [the provided link](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) `<>` "is used for system header files" and `""` "is used for header files of your own program". The TBB header files are not a part of system header files, so [the mentioned file](https://github.com/01org/tbb/blob/615bb971db8784ab6c005a856e8ed3e8cea61d9b/include/tbb/task.h#L24) should be included with the `""` syntax (because it is one of the TBB header files).

**Comment by elfring** [comment]
* How often will this software library belong to “your own program” (as a required component)?
* Do you expect that such a software library will be used from a storage location where it was installed?

-----

There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?

**Comment by alexey-katranov** [comment]
> How often will this software library belong to “your own program” (as a required component)?

The term “your own program”  is not defined. Personally, I understand it as "everything that is not C++ implementation", .i.e. any software that uses C++ but does not implement C++.

> Do you expect that such a software library will be used from a storage location where it was installed?

[`#include "tbb_stddef.h"`](https://github.com/01org/tbb/blob/615bb971db8784ab6c005a856e8ed3e8cea61d9b/include/tbb/task.h#L24) is inside `tbb/task.h`. I.e. the library header files includes some other header files from the same library. It expects that the including file resides in the same directory. If not, there is some installation issue and the library cannot be used.

> Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?

[The document says](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) that "It searches for a file named file first in the directory containing the current file", i.e. the place where the library expects other parts of itself. If the including file is not found in the current directory, the installation is broken.

> Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?

When we use `""` we expect that file will be found in "extended directories" comparing to “the angle brackets inclusion method”. Since "extended directories" should be searched first, I'd not expect performance impact of “the angle brackets inclusion method” (because it is not applied).

**Comment by elfring** [comment]
>… "It searches for a file named file first in the directory containing the current file", …

From which storage location should a library file be picked up preferably?
* Known installation directory
* Random (or temporary) software development status


>If the including file is not found in the current directory, the installation is broken.

* Can it be that software build parameters were intentionally selected in the way that questionable library files should not be found there?
* Should the use of “extended inclusion directories” be occasionally (or even mostly) excluded?

**Comment by alexey-katranov** [comment]
Let's clarify the discussed environment and consider possible options. When we are speaking about the library we also speak about an application that uses this library. Therefore, we have two questions to consider:

- How the application finds the library header files?
- How the included library (if found) finds its other parts (other header files related to this library*)?

*I suppose that the library has its own structure and may rely on this structure. If some parts of the library are separated/rearranged I consider such installation as broken and such library cannot be used.

Let's consider possible options:

- The application finds library with `<>` syntax. It means that the library is located in some "system" location. It means that library possibly can include its internal with `<>` because its internal also in "system" location.
- The application finds library with `""` syntax. It means that the library can be located in some "extended" locations. In that case library can fail to find its internals with the `<>` syntax.

From the library perspective it does not know how it is included; however, it knows its structure and may rely that the current directory is a part of the "extended" locations. Hence, the library can use the `""` syntax for the both options when includes its internals.

Let's consider the following example that demonstrates the hazard of `<>` syntax:
```
$ find . -type f -exec echo -----{}----- \; -exec cat {} \;
-----./ext.h-----
#warning ext.h
-----./lib/ext.h-----
#warning lib/ext.h
-----./lib/lib.h-----
#include <ext.h> //   <> SYNTAX
#warning lib/lib.h
-----./main.cpp-----
#include <lib/lib.h>
```
I.e. the current directory contains two files (`main.cpp` and `ext.h`) and the `lib` subdirectory with two files (`lib.h` and `ext.h`). Let's suppose that `lib.h` is a public header of some library that includes its internal file `ext.h`. If `lib.h` uses the `<>` syntax it can find another `ext.h` that is located in another directory:
```
$ g++ -c main.cpp -I.
In file included from ./lib/lib.h:1,
                 from main.cpp:1:
./ext.h:1:2: warning: #warning ext.h [-Wcpp]
 #warning ext.h
  ^~~~~~~
In file included from main.cpp:1:
./lib/lib.h:2:2: warning: #warning lib/lib.h [-Wcpp]
 #warning lib/lib.h
  ^~~~~~~
```
Pay attention that `lib/lib.h` includes `./ext.h` not `./lib/ext.h`.
Let's try the same example but `lib.h` uses the `""` syntax:
```
$ find . -type f -exec echo -----{}----- \; -exec cat {} \;
-----./ext.h-----
#warning ext.h
-----./lib/ext.h-----
#warning lib/ext.h
-----./lib/lib.h-----
#include "ext.h" //   "" SYNTAX
#warning lib/lib.h
-----./main.cpp-----
#include <lib/lib.h>
$ g++ -c main.cpp -I.
In file included from ./lib/lib.h:1,
                 from main.cpp:1:
./lib/ext.h:1:2: warning: #warning lib/ext.h [-Wcpp]
 #warning lib/ext.h
  ^~~~~~~
In file included from main.cpp:1:
./lib/lib.h:2:2: warning: #warning lib/lib.h [-Wcpp]
 #warning lib/lib.h
  ^~~~~~~
```
Now, `lib.h` includes the correct `ext.h`.

**Comment by elfring** [comment]
>If some parts of the library are separated/rearranged I consider such installation as broken and such library cannot be used.

I suggest to reconsider this kind of wording. - If specific details are changed, the corresponding software components should be adjusted as usual.


>The application finds library with "" syntax. It means that the library can be located in some "extended" locations. In that case library can fail to find its internals with the <> syntax.

* I propose to reconsider the interpretation of “extended file inclusion locations”.
* The possibility for search failures exists for both inclusion methods generally.
* Software build parameters can influence the selection of preferred storage locations for needed source files. Would you like to give any setting the priority then by a specific build option?


>Let's consider the following example that demonstrates the hazard of <> syntax:

There are development and system configuration challenges to consider as usual.
* Is an installed library version used finally?
* Do you use a library variant as a simple source code bundle?
* Which efforts do you try to separate library files from source files of a program in an application project?

**Comment by elfring** [comment]
I would appreciate another constructive feedback for this issue.

**Comment by akukanov** [comment]
@elfring, this issue is closed because it is highly unlikely that the current practice will change.

For a general discussion about the preferred syntax for a C++ library to include its own, 3rd party, and system header files, it is better to use some public forum or mailing list. We will not continue the discussion here.
